// Auto-fillable template for File for unclaimed refunds - f1310.pdf
// Generated by MapperAI - Ready for Cadence Integration

const autoFillData = {
  "topmostSubform[0].Page1[0].f1_1[0]": {{estate_reps.fiduciary_signature}},
  "topmostSubform[0].Page1[0].f1_2[0]": {{estate_reps[*].estate_name}},
  "topmostSubform[0].Page1[0].f1_3[0]": {{estate_reps[*].trade_name}},
  "topmostSubform[0].Page1[0].f1_4[0]": {{estate_reps[*].executor_name}},
  "topmostSubform[0].Page1[0].f1_5[0]": {{deceased.social_insurance_number}},
  "topmostSubform[0].Page1[0].f1_6[0]": {{applicant.full_name}},
  "topmostSubform[0].Page1[0].f1_7[0]": {{estate_reps[*].mailing_address}},
  "topmostSubform[0].Page1[0].f1_8[0]": {{estate_reps[*].mailing_address}},
  "topmostSubform[0].Page1[0].f1_9[0]": {{estate_reps[*].street_address}},
  "topmostSubform[0].Page1[0].f1_10[0]": {{estate_reps[*].street_address}},
  "topmostSubform[0].Page1[0].f1_11[0]": {{estate_reps[*].business_location}},
  "topmostSubform[0].Page1[0].f1_12[0]": {{estate_reps[*].llc_members}},
  "topmostSubform[0].Page1[0].f1_13[0]": {{deceased.social_insurance_number}},
  "topmostSubform[0].Page1[0].c1_1[0]": {{estate_reps[*].is_llc_yes}},
  "topmostSubform[0].Page1[0].c1_1[1]": {{estate_reps[*].is_llc_no}},
  "topmostSubform[0].Page1[0].c1_1[2]": {{estate_reps.authority_testate_estate}},
  "topmostSubform[0].Page1[0].c1_2[0]": {{estate_reps[*].llc_organized_us_yes}},
  "topmostSubform[0].Page1[0].c1_2[1]": {{estate_reps[*].llc_organized_us_no}},
  "topmostSubform[0].Page1[0].c1_3[0]": {{estate_reps[*].entity_sole_proprietor}},
  "topmostSubform[0].Page1[0].c1_3[1]": {{estate_reps[*].entity_partnership}},
  "topmostSubform[0].Page1[0].c1_4[0]": {{key_document[*].reason_started_business}},
  "topmostSubform[0].Page1[0].c1_4[1]": {{key_document[*].reason_purchased_business}},
  "topmostSubform[0].Page1[0].c1_5[0]": {{key_document[*].file_form_944}},
  "topmostSubform[0].Page1[0].c1_5[1]": {{applicant.agrees_to_pay_out_refund_no}},
  "topmostSubform[0].Page1[0].f1_14[0]": {{estate_reps[*].plan_administrator_tin}},
}};

// Usage Instructions:
// 1. This data structure shows how PDF fields map to Cadence paths
// 2. When integrated with Cadence, these {{}} placeholders become real data
// 3. Example: {{applicant.full_name}} becomes "John Smith" automatically

export default autoFillData;
